In [1]:
%%html
<style>
body {
    font-family: "Open Sans";
}
</style>

In [2]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

# NumPy overview
## *Vectors, Tensors and the Index Notation in NumPy*

## Authors
> Joseph Konan <jkonan@andrew.cmu.edu\> <br>

## Reference
> Kelly, Piares A. "[7.1 Vectors, Tensors and the Index Notation.](http://homepages.engineering.auckland.ac.nz/~pkel015/SolidMechanicsBooks/Part_II/07_3DElasticity/07_3DElasticity_01_3D_Index.pdf)" In Solid Mechanics Part II: Engineering Solid Mechanics, 189-200. 2012.

## Table of Contents
1. Setting-up NumPy
2. Vector Arrays
3. Matrix Array Notation
4. Tensor Arrays

## 1. Setting-up NumPy
### Installing NumPy
To install NumPy using pip:

> `python -m pip istall --user numpy scipy matplotlib ipython jupyter pandas sympy nose`

Alternative methods can be found here:

> https://scipy.org/install.html

### Importing NumPy
We import NumPy similar to how to import any other python library.

In [36]:
import numpy as np
np.random.seed(0)

print(np.version.version)
print(np.__version__)

1.16.4
1.16.4


## 2. Vector Arrays

Consider the following three coordinate vector arrays

$$ \boldsymbol{e}_1 = 
\left(\begin{array}{cc} 
1 & 0 & 0
\end{array}\right)
$$

$$ \boldsymbol{e}_2 = 
\left(\begin{array}{cc} 
0 & 1 & 0
\end{array}\right)
$$

$$ \boldsymbol{e}_3 = 
\left(\begin{array}{cc} 
0 & 0 & 1
\end{array}\right)
$$

These three vector arrays are considered orthogonal (90° angles) to eachother where none of the vectors is a scalar multiple of the others.

In [37]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

print("e1 =", e1)
print("e2 =", e2)
print("e3 =", e3)

('e1 =', array([1, 0, 0]))
('e2 =', array([0, 1, 0]))
('e3 =', array([0, 0, 1]))


The dot product of the two vector arrays is defined as

$$ \boldsymbol{a} \cdot \boldsymbol{b} = |\boldsymbol{a}| |\boldsymbol{b}| \cos \theta $$

So, because orthogonal vector arrays have $\theta = 90°$, we have  $\cos 90° = 0$. Therefore,
$$\boldsymbol{e}_1 \cdot \boldsymbol{e}_2 = \boldsymbol{e}_2 \cdot \boldsymbol{e}_3 = \boldsymbol{e}_3 \cdot \boldsymbol{e}_1 = 0$$

In [38]:
e1 = np.array([1, 0, 0])
e2 = np.array([0, 1, 0])
e3 = np.array([0, 0, 1])

print("e1⋅e2 =", np.dot(e1, e2))
print("e2⋅e3 =", np.dot(e2, e3))
print("e1⋅e3 =", np.dot(e1, e3))

('e1\xe2\x8b\x85e2 =', 0)
('e2\xe2\x8b\x85e3 =', 0)
('e1\xe2\x8b\x85e3 =', 0)


Vector arrays that are the same have $\theta=0°$, so we have $\cos0° = 1$. Therefore,

$$\boldsymbol{e}_1 \boldsymbol{e}_1 = \boldsymbol{e}_2 \boldsymbol{e}_2 = \boldsymbol{e}_3 \boldsymbol{e}_3 = 1$$

In [39]:
print("e1⋅e2 =", np.dot(e1, e1))
print("e2⋅e2 =", np.dot(e2, e2))
print("e1⋅e3 =", np.dot(e3, e3))

('e1\xe2\x8b\x85e2 =', 1)
('e2\xe2\x8b\x85e2 =', 1)
('e1\xe2\x8b\x85e3 =', 1)


We often look at scalar multiples of the coordinate vector arrays. For example, the product of scalar $a_1 = 3$ and coordinate vector array $\boldsymbol{e}_1$ is
$$
a_1 \boldsymbol{e}_1 = 3 \left(\begin{array}{cc} 
1 & 0 & 0
\end{array}\right)
=
\left(\begin{array}{cc} 
3 & 0 & 0
\end{array}\right)
$$

In [40]:
a1 = 3
e1 = np.array([1, 0, 0])

print("a1*e1 =", a1*e1)

('a1*e1 =', array([3, 0, 0]))


Consider $a_1 = 3$, $a_2 = 1$, and $a_3 = 4$

$$
\begin{aligned}
\boldsymbol{a} 
&= a_1 \boldsymbol{e}_1 + a_2 \boldsymbol{e}_2 + a_3 \boldsymbol{e}_3 \\
&= 3 \left(\begin{array}{cc} 
0 & 0 & 1
\end{array}\right) + 
1 \left(\begin{array}{cc} 
1 & 0 & 0
\end{array}\right) + 
4 \left(\begin{array}{cc} 
0 & 1 & 0
\end{array}\right) \\
&= \left(\begin{array}{cc} 
3 & 0 & 0
\end{array}\right) + 
\left(\begin{array}{cc} 
0 & 1 & 0
\end{array}\right) + 
\left(\begin{array}{cc} 
0 & 0 & 4
\end{array}\right) \\
&= \left(\begin{array}{cc} 
3 & 1 & 4
\end{array}\right)
\end{aligned}
$$

In [41]:
a1 = 3
a2 = 1
a3 = 4

a = a1*e1 + a2*e2 + a3*e3

print("a = a1*e1 + a2*e2 + a3*e3 =", a)

('a = a1*e1 + a2*e2 + a3*e3 =', array([3, 1, 4]))


We can also write the sum of scaled coordinates in summation notation:
$$ \boldsymbol{a} = a_1 \boldsymbol{e}_1 + a_2 \boldsymbol{e}_2 + a_3 \boldsymbol{e}_3 = \sum_{i=1}^{3}a_i \boldsymbol{e}_i $$

In [42]:
components = [a1, a2, a3]
vectors = [e1, e2, e3]

a = np.zeros(3)
for i in range(len(components)):
    a += components[i]*vectors[i]

print("sum of {i=1} to {3} of {ai ei} =", a)

('sum of {i=1} to {3} of {ai ei} =', array([3., 1., 4.]))


In [43]:
a = np.zeros(3)
for component, vector in zip(components, vectors):
    a += component*vector
    
print("sum of each {component} in {components} =", a)

('sum of each {component} in {components} =', array([3., 1., 4.]))


If we are looking at the dot product for more general vector arrays, we can use what we saw so far. The result should be familiar:

$$
\begin{align}
\boldsymbol{u} ⋅ \boldsymbol{v} & = 
(u_1 \boldsymbol{e}_1 + u_2 \boldsymbol{e}_2 + u_3 \boldsymbol{e}_3)⋅(v_1 \boldsymbol{e}_1 + v_2 \boldsymbol{e}_2 + v_3 \boldsymbol{e}_3)
\\\\ & = 
u_1v_1( \boldsymbol{e}_1 \boldsymbol{e}_1) + u_1v_2( \boldsymbol{e}_1 \boldsymbol{e}_2) + u_1v_3( \boldsymbol{e}_1 \boldsymbol{e}_3)
\\\\ & \quad+
u_2v_1( \boldsymbol{e}_2 \boldsymbol{e}_1) + u_2v_2( \boldsymbol{e}_2 \boldsymbol{e}_2) + u_2v_3( \boldsymbol{e}_2 \boldsymbol{e}_3)
\\\\ & \quad+
u_3v_1( \boldsymbol{e}_3 \boldsymbol{e}_1) + u_3v_2( \boldsymbol{e}_3 \boldsymbol{e}_2) + u_3v_3( \boldsymbol{e}_3 \boldsymbol{e}_3)
\\\\ & =
u_1v_1 + u_2v_2 + u_3v_3
\end{align}\\
$$

Consider 
$u = \left(\begin{array}{cc} 
3 & 1 & 4
\end{array}\right)$
, and 
$v = \left(\begin{array}{cc} 
1 & 5 & 9
\end{array}\right)$, then:

$$
\begin{aligned}
\boldsymbol{u} \cdot \boldsymbol{v}
&= u_1 v_1 + u_2 v_2 + u_3 v_3 \\
&= (3) (1) + (1) (5) + (4) (9) \\
&= 44
\end{aligned}
$$

In [44]:
u_components = [3, 1, 4]
v_components = [1, 5, 9]

u = u_components[0]*e1 + u_components[1]*e2 + u_components[2]*e3
v = v_components[0]*e1 + v_components[1]*e2 + v_components[2]*e3

result = np.dot(u, v)
print(result)

44


$$\boldsymbol{u}⋅\boldsymbol{v}=\sum_{i=1}^{3}\sum_{j=1}^{3}u_iv_j(e_ie_j)$$

In [45]:
e = [e1, e2, e3]

# Another way to write the dot product using for loops
result = 0
for i in range(len(e)):
    for j in range(len(e)): 
        result += u_components[i]*v_components[j]*(np.dot(e[i],e[j]))
print(result)

44


We can also directly declare these vector arrays:

In [46]:
u = np.array(u_components)
v = np.array(v_components)

result = u[0]*v[0] + u[1]*v[1] + u[2]*v[2]
print(result)

44


Since we only use the indicies at unity, we can simplify the for loop:
$$\boldsymbol{u}⋅\boldsymbol{v}=\sum_{i=1}^{3}u_iv_i$$

In [47]:
result = 0
for i in range(len(u)):
    result += u[i]*v[i]
print(result)

44


And this is all equivalent to the vectorization:

In [48]:
result = np.dot(u, v)
print(result)

44


A more formal way of writing when indicies are the same yielding unity is with Kronecker delta, which is defined as:
$$
\delta_{ij}=   \left\{
\begin{array}{ll}
      0, & i \neq j \\
      1, & i = j \\
\end{array} 
\right.
$$

In the code we write the conditional, simply as:

In [49]:
def kron(i,j):
    if i == j:
        return 1
    else:
        return 0
    
print(kron(1, 1))
print(kron(1, 2))

1
0


Which is the same as looking at the dot product of coordinate vector arrays with respect to their index.
$$ \boldsymbol{e}_i⋅\boldsymbol{e}_j=\delta_{ij} $$
And just to confirm, we can see the reult is the same for all cases in our example:

In [50]:
e = [e1, e2, e3]
for i in range(len(e)):
    for j in range(len(e)):
        print(np.dot(e[i],e[j]), "=", kron(i, j))

(1, '=', 1)
(0, '=', 0)
(0, '=', 0)
(0, '=', 0)
(1, '=', 1)
(0, '=', 0)
(0, '=', 0)
(0, '=', 0)
(1, '=', 1)


## 3. Matrix Array Notation

Here is a $3 \times 1$ matrix array:
$$
\boldsymbol{u} =
\left(\begin{array}{cc} 
u_1\\
u_2\\
u_3
\end{array}\right)
\Rightarrow
\boldsymbol{u}^T =
\left(\begin{array}{cc} 
u_1 &
u_2 &
u_3
\end{array}\right)
$$ 

In [51]:
# Create a random 3 x 1 matrix array from a uniform distribution from 0 to 1
u = np.random.random((3,1))
print("u =\n", u)
print("u^T =\n", u.T)

('u =\n', array([[0.5488135 ],
       [0.71518937],
       [0.60276338]]))
('u^T =\n', array([[0.5488135 , 0.71518937, 0.60276338]]))


$$
\boldsymbol{v} = 
\left(\begin{array}{cc} 
v_1\\
v_2\\
v_3
\end{array}\right)
\Rightarrow
\boldsymbol{v}^T = 
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right)
$$

In [52]:
# Create a random 3 x 1 matrix array from a uniform distribution from 0 to 1
v = np.random.random((3,1))

# Transposing it yields a 1 x 3 matrix array
print("v =\n", v)
print("v^T =\n", v.T)

('v =\n', array([[0.54488318],
       [0.4236548 ],
       [0.64589411]]))
('v^T =\n', array([[0.54488318, 0.4236548 , 0.64589411]]))


An example of matrix multiplication:

$$
\boldsymbol{u}^T\boldsymbol{v} =
\left(\begin{array}{cc} 
u_1 & u_2 & u_3
\end{array}\right)
\left(\begin{array}{cc} 
v_1 \\ v_2 \\ v_3
\end{array}\right)
= \left(\begin{array}{cc} 
u_1 v_1 + u_2 v_2 + u_3 v_3
\end{array}\right)
$$

In [53]:
result = np.matmul(u.T, v)
print("u^T⋅v =\n", result)

('u^T\xe2\x8b\x85v =\n', array([[0.99135397]]))


The $3 \times 3$ identity matrix array:

$$\boldsymbol{I} = 
\left(\begin{array}{cc} 
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{array}\right)
$$ 

In [54]:
I = np.eye(3)

print("I =\n", I)

('I =\n', array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))


$$\delta_{ij}u_j=u_i$$
$$ \boldsymbol{I}\boldsymbol{u} = \boldsymbol{u} $$
$$
\left(\begin{array}{cc} 
1 & 0 & 0\\
0 & 1 & 0\\
0 & 0 & 1
\end{array}\right)
\left(\begin{array}{cc} 
u_1\\
u_2\\
u_3
\end{array}\right)
=
\left(\begin{array}{cc} 
u_1\\
u_2\\
u_3
\end{array}\right)
$$

In [55]:
u = np.random.random((3, 1))
result = np.dot(I, u)

print("I =\n", I)

print("u =\n", u)

print("I⋅u =\n", result)

('I =\n', array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]]))
('u =\n', array([[0.43758721],
       [0.891773  ],
       [0.96366276]]))
('I\xe2\x8b\x85u =\n', array([[0.43758721],
       [0.891773  ],
       [0.96366276]]))


Here is an example of matrix array multiplication between a $3 \times 1$ matrix array and a $1 \times 3$ matrix array:
$$
\boldsymbol{u} \boldsymbol{v}^T=
\left(\begin{array}{cc} 
u_1 \\
u_2 \\
u_3
\end{array}\right)
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right)
=
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3\\
u_2v_1 & u_2v_2 & u_2v_3\\
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
$$ 

In [56]:
u = np.array([[1, 2, 3]])
v = np.array([[4, 5, 6]])

result = np.matmul(u.T, v)

print("u v^T =\n", result)

('u v^T =\n', array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]]))


$$
\begin{aligned}
u \otimes v 
&=  
\left(\begin{array}{cc} 
u_1
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right) 
\\
u_2
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right) 
\\
u_3
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right)
\end{array}\right) \\
&=  
\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3
\end{array}\right) 
\\
\left(\begin{array}{cc} 
u_2v_1 & u_2v_2 & u_2v_3
\end{array}\right) 
\\
\left(\begin{array}{cc} 
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
\end{array}\right) \\
&=
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3\\
u_2v_1 & u_2v_2 & u_2v_3\\
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
\end{aligned}
$$

In [57]:
# Squeezing the matrix (2D) arrays makes them vector (1D) arrays
u = u.squeeze()
v = v.squeeze()

result = np.tensordot(u, v, axes=0)

print("u⨂v =\n", result)

('u\xe2\xa8\x82v =\n', array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]]))


Here is an example of matrix array multiplication between a $3 \times 3$ matrix array and a $3 \times 1$ vector arrays:
$$
\boldsymbol{Q} \boldsymbol{u}
=
\left(\begin{array}{cc} 
Q_{11} & Q_{12} & Q_{13}\\
Q_{21} & Q_{22} & Q_{23}\\
Q_{31} & Q_{32} & Q_{33}
\end{array}\right)
\left(\begin{array}{cc} 
u_{1}\\
u_{2}\\
u_{3}
\end{array}\right)
= 
\left(\begin{array}{cc} 
Q_{11} u_{1} + Q_{12} u_{2} + Q_{13} u_{3}\\
Q_{21} u_{1} + Q_{22} u_{2} + Q_{23} u_{3}\\
Q_{31} u_{1} + Q_{32} u_{2} + Q_{33} u_{3}
\end{array}\right)
$$ 

This is NOT equivalent to the tensor array product of a matrix array and a vector array. More on this later.

In [58]:
Q = np.random.randint(9, size=(3,3))
u = np.array([[1], 
              [2], 
              [3]])

result = np.matmul(Q, u)

print("Q =\n", Q)

print("u =\n", u)

print("Q⋅u =\n", result)

('Q =\n', array([[1, 6, 7],
       [7, 8, 1],
       [5, 8, 4]]))
('u =\n', array([[1],
       [2],
       [3]]))
('Q\xe2\x8b\x85u =\n', array([[34],
       [26],
       [33]]))


$$(\boldsymbol{A}\boldsymbol{B})^T = \boldsymbol{B}^T\boldsymbol{A}^T$$

In [59]:
A = np.random.randint(9, size=(3,3))
B = np.random.randint(9, size=(3,3))

result = np.dot(A, B).T

print("A =\n", A)

print("B =\n", B)

print("(A⋅B)^T =\n", result)

('A =\n', array([[3, 0, 3],
       [5, 0, 2],
       [3, 8, 1]]))
('B =\n', array([[3, 3, 3],
       [7, 0, 1],
       [0, 4, 7]]))
('(A\xe2\x8b\x85B)^T =\n', array([[ 9, 15, 65],
       [21, 23, 13],
       [30, 29, 24]]))


In [60]:
result = np.dot(B.T, A.T)

print("A^T =\n", A.T)

print("B^T =\n", B.T)

print("A^T⋅B^T =\n", result)

('A^T =\n', array([[3, 5, 3],
       [0, 0, 8],
       [3, 2, 1]]))
('B^T =\n', array([[3, 7, 0],
       [3, 0, 4],
       [3, 1, 7]]))
('A^T\xe2\x8b\x85B^T =\n', array([[ 9, 15, 65],
       [21, 23, 13],
       [30, 29, 24]]))


## 4. Tensor Arrays

Consider this vector arrays with 3 components:

$$
\left(\begin{array}{cc} 
a_{0} \\ a_{1} \\ a_{2}
\end{array}\right)
$$ 

And consider this $4 \times 4$ matrix array:
$$
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right)
$$ 

Then the tensor array product of the vector arrays and the matrix array is calculated as follows:

$
\left(\begin{array}{cc} 
a_{0} \\ a_{1} \\ a_{2}
\end{array}\right)
\otimes
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right)
$


$
\begin{aligned}
\: \: \: \: \: \: \: \: &=
\left(\begin{array}{cc} 
a_{0}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) \\
a_{1}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) \\
a_{2}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) 
\end{array}\right) \\ &=
\left(\begin{array}{cc} 
a_{0}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) ,
a_{1}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) ,
a_{2}
\left(\begin{array}{cc} 
b_{00} & b_{01} & b_{02} & b_{03}\\
b_{10} & b_{11} & b_{12} & b_{13}\\
b_{20} & b_{21} & b_{22} & b_{23}\\
b_{30} & b_{31} & b_{32} & b_{33}
\end{array}\right) 
\end{array}\right) \\
&=
\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
a_{0}b_{00} & a_{0}b_{01} & a_{0}b_{02} & a_{0}b_{03}\\
a_{0}b_{10} & a_{0}b_{11} & a_{0}b_{12} & a_{0}b_{13}\\
a_{0}b_{20} & a_{0}b_{21} & a_{0}b_{22} & a_{0}b_{23}\\
a_{0}b_{30} & a_{0}b_{31} & a_{0}b_{32} & a_{0}b_{33}
\end{array}\right)
,
\left(\begin{array}{cc} 
a_{1}b_{00} & a_{1}b_{01} & a_{1}b_{02} & a_{1}b_{03}\\
a_{1}b_{10} & a_{1}b_{11} & a_{1}b_{12} & a_{1}b_{13}\\
a_{1}b_{20} & a_{1}b_{21} & a_{1}b_{22} & a_{1}b_{23}\\
a_{1}b_{30} & a_{1}b_{31} & a_{1}b_{32} & a_{1}b_{33}
\end{array}\right)
,
\left(\begin{array}{cc} 
a_{2}b_{00} & a_{2}b_{01} & a_{2}b_{02} & a_{2}b_{03}\\
a_{2}b_{10} & a_{2}b_{11} & a_{2}b_{12} & a_{2}b_{13}\\
a_{2}b_{20} & a_{2}b_{21} & a_{2}b_{22} & a_{2}b_{23}\\
a_{2}b_{30} & a_{2}b_{31} & a_{2}b_{32} & a_{2}b_{33}
\end{array}\right)
\end{array}\right) \\
&=
\left(\begin{array}{cc} 
\left(\begin{array}{cc} 
\tau_{000} & \tau_{001} & \tau_{002} & \tau_{003}\\
\tau_{010} & \tau_{011} & \tau_{012} & \tau_{013}\\
\tau_{020} & \tau_{021} & \tau_{022} & \tau_{023}\\
\tau_{030} & \tau_{031} & \tau_{032} & \tau_{033}
\end{array}\right)
,
\left(\begin{array}{cc} 
\tau_{100} & \tau_{101} & \tau_{102} & \tau_{103}\\
\tau_{110} & \tau_{111} & \tau_{112} & \tau_{113}\\
\tau_{120} & \tau_{121} & \tau_{122} & \tau_{123}\\
\tau_{130} & \tau_{131} & \tau_{132} & \tau_{133}
\end{array}\right)
,
\left(\begin{array}{cc} 
\tau_{200} & \tau_{201} & \tau_{202} & \tau_{203}\\
\tau_{210} & \tau_{211} & \tau_{212} & \tau_{213}\\
\tau_{220} & \tau_{221} & \tau_{222} & \tau_{223}\\
\tau_{230} & \tau_{231} & \tau_{232} & \tau_{233}
\end{array}\right)
\end{array}\right)
\end{aligned}
$

This tensor array could be described as a 3D matrix array.

In [61]:
!ls ../img

3d_array.png  tensor2.png  tensor4.png	tensor6.png
tensor1.png   tensor3.png  tensor5.png	tensor7.png


<img src="../img/tensor1.png" alt="Image of Rank 3 Tensor" style="width: 500px;"/>

In [62]:
A = np.random.randint(9, size=(3))
B = np.random.randint(9, size=(4,4))

print("A = \n", A)

print("B = \n", B)

print("A⨂B =\n", np.tensordot(A, B, axes=0))

('A = \n', array([3, 2, 7]))
('B = \n', array([[2, 0, 0, 4],
       [5, 5, 6, 8],
       [4, 1, 4, 8],
       [1, 1, 7, 3]]))
('A\xe2\xa8\x82B =\n', array([[[ 6,  0,  0, 12],
        [15, 15, 18, 24],
        [12,  3, 12, 24],
        [ 3,  3, 21,  9]],

       [[ 4,  0,  0,  8],
        [10, 10, 12, 16],
        [ 8,  2,  8, 16],
        [ 2,  2, 14,  6]],

       [[14,  0,  0, 28],
        [35, 35, 42, 56],
        [28,  7, 28, 56],
        [ 7,  7, 49, 21]]]))


### Consider this list of matrices

In [63]:
a1 = np.array([np.array([3, 1, 4, 1]), 
               np.array([5, 9, 2, 6]), 
               np.array([5, 3, 5, 8])])

a2 = np.array([np.array([9, 7, 9, 3]),
               np.array([2, 3, 8, 4])])

a3 = np.array([np.array([3, 3, 8, 3]), 
               np.array([2, 7, 9, 5]),
               np.array([0, 2, 8, 8]), 
               np.array([6, 2, 6, 4])])

A = np.array([a1, a2, a3])

print("A =\n", A.T)

('A =\n', array([array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]]),
       array([[9, 7, 9, 3],
       [2, 3, 8, 4]]),
       array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])], dtype=object))


<img src="../img/tensor2.png" alt="Image of Rank 3 Tensor" style="width: 500px;"/>

### How to subset the first two elements to make a tensor array

In [64]:
A1 = [record[:2] for record in A]
A1 = np.array(A1)

print("A =\n", A)

print("A1 =\n", A1)

('A =\n', array([array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]]),
       array([[9, 7, 9, 3],
       [2, 3, 8, 4]]),
       array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])], dtype=object))
('A1 =\n', array([[[3, 1, 4, 1],
        [5, 9, 2, 6]],

       [[9, 7, 9, 3],
        [2, 3, 8, 4]],

       [[3, 3, 8, 3],
        [2, 7, 9, 5]]]))


<img src="../img/tensor3.png" alt="Image of Rank 3 Tensor" style="width: 500px;"/>

### How to subset the last two elements to make a tensor array

In [65]:
A2 = [record[-2:] for record in A]
A2 = np.array(A2)

print("A =\n", A)

print("A2 =\n", A2)

('A =\n', array([array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]]),
       array([[9, 7, 9, 3],
       [2, 3, 8, 4]]),
       array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])], dtype=object))
('A2 =\n', array([[[5, 9, 2, 6],
        [5, 3, 5, 8]],

       [[9, 7, 9, 3],
        [2, 3, 8, 4]],

       [[0, 2, 8, 8],
        [6, 2, 6, 4]]]))


<img src="../img/tensor4.png" alt="Image of Rank 3 Tensor" style="width: 500px;"/>

### How to pad at the bottom to make a tensor array

In [66]:
pad_below1 = 4 - len(a1)
pad_below2 = 4 - len(a2)
pad_below3 = 4 - len(a3)

pad_above = 0
pad_left = 0
par_right = 0

n_add = [((pad_above, pad_below1), (pad_left, par_right)), 
         ((pad_above, pad_below2), (pad_left, par_right)), 
         ((pad_above, pad_below3), (pad_left, par_right))]

A3 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A3 = np.array(A3)

print("A =\n", A)

print("A3 =\n", A3)

('A =\n', array([array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]]),
       array([[9, 7, 9, 3],
       [2, 3, 8, 4]]),
       array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])], dtype=object))
('A3 =\n', array([[[3, 1, 4, 1],
        [5, 9, 2, 6],
        [5, 3, 5, 8],
        [0, 0, 0, 0]],

       [[9, 7, 9, 3],
        [2, 3, 8, 4],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[3, 3, 8, 3],
        [2, 7, 9, 5],
        [0, 2, 8, 8],
        [6, 2, 6, 4]]]))


<img src="../img/tensor5.png" alt="Image of Rank 3 Tensor" style="width: 500px;"/>

### How to pad at the top to make a tensor array

In [67]:
pad_above1 = 4 - len(a1)
pad_above2 = 4 - len(a2)
pad_above3 = 4 - len(a3)

pad_below = 0
pad_left = 0
par_right = 0

n_add = [((pad_above1, pad_below), (pad_left, par_right)), 
         ((pad_above2, pad_below), (pad_left, par_right)), 
         ((pad_above3, pad_below), (pad_left, par_right))]

A4 = [np.pad(A[i], pad_width = n_add[i], mode = 'constant', constant_values = 0) for i in range(3)]
A4 = np.array(A4)

print("A =\n", A)

print("A4 =\n", A4)

('A =\n', array([array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]]),
       array([[9, 7, 9, 3],
       [2, 3, 8, 4]]),
       array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])], dtype=object))
('A4 =\n', array([[[0, 0, 0, 0],
        [3, 1, 4, 1],
        [5, 9, 2, 6],
        [5, 3, 5, 8]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [9, 7, 9, 3],
        [2, 3, 8, 4]],

       [[3, 3, 8, 3],
        [2, 7, 9, 5],
        [0, 2, 8, 8],
        [6, 2, 6, 4]]]))


<img src="../img/tensor6.png" alt="Image of Rank 3 Tensor" style="width: 500px;"/>

### How to vertically stack the 3D object to make a 2D matrix array

In [68]:
A5 = np.vstack(A)

print("A =\n", A)

print("A5 =\n", A5)

('A =\n', array([array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8]]),
       array([[9, 7, 9, 3],
       [2, 3, 8, 4]]),
       array([[3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]])], dtype=object))
('A5 =\n', array([[3, 1, 4, 1],
       [5, 9, 2, 6],
       [5, 3, 5, 8],
       [9, 7, 9, 3],
       [2, 3, 8, 4],
       [3, 3, 8, 3],
       [2, 7, 9, 5],
       [0, 2, 8, 8],
       [6, 2, 6, 4]]))


<img src="../img/tensor7.png" alt="Image of Rank 3 Tensor" style="width: 300px;"/>